name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Debug - List files in current directory
      run: |
        echo "Current working directory: $(pwd)"
        ls -la

    - name: Change to the correct directory
      run: cd project  # package.json dosyanızın bulunduğu dizin

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # Derleme sonucu çıkan dizin
